<?php

namespace App\Http\Controllers;

use App\Models\Stock;
use App\Services\TradingDayService;
use Illuminate\Support\Collection;
use Illuminate\View\View;

class StockAnalysisController extends Controller
{
    /**
     * Inject the trading-day service used to resolve the default analysis date.
     */
    public function __construct(private TradingDayService $tradingDay) {}

    /**
     * Render the stock analysis page.
     *
     * Phase 1 uses GoAPI (free tier) which supports: price/volume (historical),
     * PV analysis (historical), technical (indicators), and broker-level
     * widgets (broker_summary + daily aggregates). Done/detail transactions
     * stay commented — GoAPI has no per-order tape.
     *
     * Dev data is generated by symbol-seeded mock builders spanning ~2 months
     * so accumulation/inventory trends are visible. Replace the builders with
     * GoApiService calls (DB-backed daily ingestion) when wiring the API.
     */
    public function index(): View
    {
        $stocks = Stock::orderBy('code')->get(['code', 'name']);
        $tradeDay = $this->tradingDay->defaultTradeDay();
        // ponytail: dev default symbol; seeded by symbol so any ticker works. Add ?symbol= wiring later.
        $symbol = $stocks->first()->code ?? 'BBCA';

        $buyers = $this->mockLeaders('buy', $symbol);
        $sellers = $this->mockLeaders('sell', $symbol);
        $retail = $this->mockRetail($symbol);

        $buyersCls = $this->classifyBuyers($buyers);
        $sellersCls = $this->classifySellers($sellers);

        $accumulation = $this->mockAccumulation($tradeDay, $symbol);
        $inventory = $this->mockInventory($symbol, $tradeDay);

        // broker-summary wants lighter rows (vol/val/avg as strings — UI mock shape).
        $buyers = collect($buyers)->map(fn ($b) => [
            'code' => $b['code'], 'vol' => number_format(($this->seed($symbol.$b['code']) * 4000) + 1000),
            'val' => number_format($this->seed($symbol.$b['code']) * 50, 1), 'avg' => '10,2'.rand(10, 29),
        ])->all();
        $sellers = collect($sellers)->map(fn ($s) => [
            'code' => $s['code'], 'vol' => number_format(($this->seed($symbol.$s['code']) * 4000) + 1000),
            'val' => number_format($this->seed($symbol.$s['code']) * 50, 1), 'avg' => '10,2'.rand(10, 29),
        ])->all();

        // ponytail: kept here to avoid touching the technical widget — forward the same shape.
        // Derivable from GoAPI historical OHLC; replace with live pattern detection later.
        $techPatterns = [
            ['name' => 'Double Bottom', 'type' => 'Reversal', 'tp' => '10,650', 'sl' => '9,900', 'status' => 'Confirmed'],
            ['name' => 'Bullish Flag', 'type' => 'Continuation', 'tp' => '10,800', 'sl' => '10,050', 'status' => 'Forming'],
            ['name' => 'Triangle', 'type' => 'Continuation', 'tp' => '10,500', 'sl' => '9,950', 'status' => 'Forming'],
        ];

        return view('stock.analyze', compact(
            'stocks', 'tradeDay', 'buyers', 'sellers', 'buyersCls', 'sellersCls', 'retail', 'techPatterns', 'accumulation', 'inventory'
        ));
    }

    /**
     * Build the broker-inventory chart dataset (~60 days, symbol-seeded).
     *
     * Generates 60 daily points of deterministic cumulative net per broker
     * (AK/BK/CC/PD accumulate, YP/ZP/YU distribute), a synthetic price line,
     * the Top-3 accumulators/distributors, Net Bandar total, and an AI
     * bandarmology phase/score/summary. Replace with GoAPI broker_summary
     * daily ingestion once the API is wired.
     */
    private function mockInventory(string $symbol, string $tradeDay): array
    {
        $codes = ['AK', 'BK', 'CC', 'PD', 'YP', 'ZP', 'YU'];
        $end = \Carbon\Carbon::parse($tradeDay);
        $dates = [];
        $d = $end->copy()->subDays(59);
        for ($i = 0; $i < 60; $i++) {
            $dates[] = $d->copy()->addDays($i)->format('Y-m-d');
        }

        $series = [];
        $accum = [];
        $dist = [];
        foreach ($codes as $code) {
            $r = $this->seed($symbol.$code.'inv');
            $sign = in_array($code, ['ZP', 'YU', 'YP']) ? -1 : 1;
            $cum = 0;
            $points = [];
            foreach ($dates as $j => $date) {
                $step = round($sign * ($r * 400 + 50) * (0.6 + 0.4 * sin($j / 4)));
                $cum += $step;
                $points[] = ['time' => $date, 'value' => $cum];
            }
            $series[] = [
                'code' => $code,
                'name' => $code,
                'side' => $sign > 0 ? 'buy' : 'sell',
                'data' => $points,
            ];
            if ($sign > 0) {
                $accum[] = ['code' => $code, 'name' => $code, 'end' => $cum];
            } else {
                $dist[] = ['code' => $code, 'name' => $code, 'end' => $cum];
            }
        }

        $price = collect($dates)->map(function ($date, $j) {
            return ['time' => $date, 'value' => round(9800 + 600 * sin($j / 5) + $j * 12, 0)];
        })->all();

        $netBandar = collect($series)->sum(fn ($s) => end($s['data'])['value']);
        $score = $netBandar >= 0 ? min(100, 50 + (int) ($netBandar / 5000)) : max(0, 50 + (int) ($netBandar / 5000));

        return [
            'dates' => $dates,
            'price' => $price,
            'series' => $series,
            'topAccum' => collect($accum)->sortByDesc('end')->take(3)->values()->all(),
            'topDist' => collect($dist)->sortBy('end')->take(3)->values()->all(),
            'netBandar' => (int) $netBandar,
            'score' => (int) $score,
            'phase' => $score >= 60 ? 'Mark-Up / Accumulation' : ($score <= 40 ? 'Distribution' : 'Consolidation'),
            'summary' => $score >= 60
                ? 'Price making higher lows while Net Bandar inventory stays positive — classic Mark-Up phase. Major accumulator leading the charge; distribution risk low unless price stalls above target.'
                : ($score <= 40
                    ? 'Net Bandar inventory flipping negative with price unable to hold gains — Distribution phase underway. Watch for breakdown below AVG support.'
                    : 'Bandar inventory balanced; price coiling in range. Waiting for expansion — accumulation vs distribution not yet decisive.'),
        ];
    }

    /**
     * Build the accumulation-range & bandar AVG dataset (multi-day, symbol-seeded).
     *
     * Derives per-broker net lot / average price / value deterministically,
     * ranks the Top-3 accumulators, and computes the Bandar AVG plus
     * current/SL/target levels. Range spans ~2 months ending at $tradeDay.
     * Replace with GoAPI broker_summary accumulated-net-per-period later.
     */
    private function mockAccumulation(string $tradeDay, string $symbol): array
    {
        $codes = ['AK', 'YP', 'CC', 'BK', 'PD', 'NI'];
        $rows = [];
        $totalLot = 0;
        $totalVal = 0;
        foreach ($codes as $code) {
            $r = $this->seed($symbol.$code.'acc');
            $netLot = (int) ($r * 800000) + 50000;
            $avgPrice = (int) (($r * 200) + 9800);
            $netValue = $netLot * $avgPrice;
            $totalLot += $netLot;
            $totalVal += $netValue;
            $rows[] = [
                'code' => $code,
                'name' => $code,
                'netLot' => $netLot, 'avgPrice' => $avgPrice, 'netValue' => $netValue,
            ];
        }
        $rows = collect($rows)->sortByDesc('netLot')->values();
        $top3 = $rows->take(3)->map(fn ($b) => [...$b, 'concentration' => round($b['netLot'] / max($totalLot, 1) * 100)])->all();

        $bandarAvg = (int) $rows->avg('avgPrice');
        $current = (int) ($bandarAvg * 1.04); // +4% -> Safe Entry Zone

        return [
            'start' => \Carbon\Carbon::parse($tradeDay)->subDays(59)->format('Y-m-d'),
            'end' => $tradeDay,
            'tradingDays' => 60,
            'top3' => $top3,
            'totalNetLot' => $totalLot,
            'totalNetValue' => $totalVal,
            'bandarAvg' => $bandarAvg,
            'currentPrice' => $current,
            'sl' => (int) ($bandarAvg * 0.94),
            'target' => (int) ($bandarAvg * 1.15),
        ];
    }

    /**
     * Deterministic pseudo-random in [0.001, 1.0] from a seed key.
     *
     * Keeps dev data stable across reloads without a faker dependency.
     */
    private function seed(string $key): float
    {
        return ((crc32($key) % 1000) + 1) / 1000; // 0.001 - 1.0
    }

    /**
     * Build the buyer/seller leaderboard rows (symbol-seeded).
     *
     * @param  string  $side  'buy' or 'sell' (flips the net sign).
     * @return array<int,array{code:string,inv:string,net:float,pct:int}>
     */
    private function mockLeaders(string $side, string $symbol): array
    {
        $codes = ['YP', 'AK', 'PD', 'BK', 'KZ', 'AZ', 'XL', 'NI', 'CS', 'RX'];
        $rows = [];
        foreach ($codes as $code) {
            $r = $this->seed($symbol.$code.$side);
            $net = round($r * 60, 1) * ($side === 'buy' ? 1 : -1);
            $rows[] = [
                'code' => $code,
                'inv' => in_array($code, ['AK', 'BK', 'PD', 'YP', 'KZ', 'AZ']) ? 'F' : 'D',
                'net' => $net,
                'pct' => (int) ($r * 80 + 10),
            ];
        }
        usort($rows, fn ($a, $b) => $side === 'buy' ? $b['net'] <=> $a['net'] : $a['net'] <=> $b['net']);

        return $rows;
    }

    /**
     * Flag buyers acting as retail impostors (YP with >=70% HAKA).
     *
     * @return array<int,array{code:string,inv:string,net:float,pct:int,impostor:bool}>
     */
    private function classifyBuyers(array $rows): array
    {
        return collect($rows)->map(function ($r) {
            $impostor = $r['code'] === 'YP' && $r['pct'] >= 70;

            return [...$r, 'impostor' => $impostor];
        })->all();
    }

    /**
     * Sellers are never flagged as impostors in the current mock.
     *
     * @return array<int,array{code:string,inv:string,net:float,pct:int,impostor:bool}>
     */
    private function classifySellers(array $rows): array
    {
        return collect($rows)->map(fn ($r) => [...$r, 'impostor' => false])->all();
    }

    /**
     * Build the retail-broker behavioral dataset (HAKA/HAKI, avg lot, score).
     *
     * @return array<int,array{code:string,name:string,tx:int,vol:int,avgLot:int,haka:int,haki:int,score:int,diagnosis:string}>
     */
    private function mockRetail(string $symbol): array
    {
        $codes = ['YP', 'CC', 'PD', 'XC', 'NI'];

        return collect($codes)->map(function ($code) use ($symbol) {
            $r = $this->seed($symbol.$code.'retail');
            $avgLot = (int) ($r * 6000) + 50;
            $haka = (int) ($r * 60) + 20;
            $score = $avgLot > 2500 ? (int) ($r * 40) + 65 : (int) ($r * 50) + 5;
            $diag = $score > 65 ? 'Stealth Accumulation' : ($score >= 30 ? 'Mixed Activity' : 'Genuine Retail');

            return [
                'code' => $code, 'name' => $code,
                'tx' => (int) ($r * 150) + 20,
                'vol' => (int) ($r * 240000) + 5000,
                'avgLot' => $avgLot,
                'haka' => $haka, 'haki' => 100 - $haka,
                'score' => $score, 'diagnosis' => $diag,
            ];
        })->all();
    }
}
